#!/bin/bash

cd $HOME/.werewolf
git pull
cd $HOME/.werewolf/server
echo "#define DRIVER_TYPE_HARDWARE" > v0.2/hardware.h
pio run -e megaatmega2560 -t upload
echo "#define DRIVER_TYPE_COMPUTER" > v0.2/hardware.h

exit